export enum MimeType {
    turtle = 'text/turtle',
    ntriples = 'application/n-triples',
    rdfxml = 'application/rdf+xml',
    trig = 'application/trig',
    nquads = 'application/n-quads',
    json = 'application/json',
    sparqlResultsJson = 'application/sparql-results+json',
    sparqlResultsXml = 'application/sparql-results+xml',
    sparqlResultsCsv = 'text/csv; charset=utf-8',
    sparqlResultsTsv = 'text/tab-separated-values; charset=utf-8',
    sparqlQuery = 'application/sparql-query',
    sparqlUpdate = 'application/sparql-update',
    plainText = 'text/plain',
    any = '*/*',
}
